### ISSUE TITLE
what the version scikit-image is?

### ISSUE THREAD

**Issue by HFXxXx** [VieVie31/scene_detection#1]
ImportError: cannot import name 'rgb2grey' from 'skimage.color'
cant import the rgb2grey
and in the. __init__.py also cant find the rgb2grey but only has rgb2gray

**Comment by VieVie31** [comment]
Hello ! 

This project is super old, unfortunately it seems I was not really doing a good job with requirements.txt :p
But, after a quick check, it's maybe around the 0.11.x ? For exemple you can see at this address that `rgb2grey` existed at this time : https://scikit-image.org/docs/0.11.x/api/skimage.color.html#rgb2grey 🦖 

Good luck ! 🤞🏻
